In [31]:
import pandas as pd
import numpy as np
df = pd.read_excel("default of credit card clients.xls", header=1)
df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

In [32]:
df.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month'],
      dtype='object')

In [33]:
df = df.rename(columns={
    "ID": "Customer_ID",
    "LIMIT_BAL": "Credit_Limit",
    "SEX": "Gender",
    "EDUCATION": "Education",
    "MARRIAGE": "Marital_Status",
    "AGE": "Age",
    "PAY_0": "Pay_Status_Sept",
    "PAY_2": "Pay_Status_Aug",
    "PAY_3": "Pay_Status_July",
    "PAY_4": "Pay_Status_June",
    "PAY_5": "Pay_Status_May",
    "PAY_6": "Pay_Status_April",
    "BILL_AMT1": "Bill_Sept",
    "BILL_AMT2": "Bill_Aug",
    "BILL_AMT3": "Bill_July",
    "BILL_AMT4": "Bill_June",
    "BILL_AMT5": "Bill_May",
    "BILL_AMT6": "Bill_April",
    "PAY_AMT1": "Payment_Sept",
    "PAY_AMT2": "Payment_Aug",
    "PAY_AMT3": "Payment_July",
    "PAY_AMT4": "Payment_June",
    "PAY_AMT5": "Payment_May",
    "PAY_AMT6": "Payment_April",
    "default payment next month": "Default_Next_Month"
})

In [34]:
print(df.columns.tolist())

['Customer_ID', 'Credit_Limit', 'Gender', 'Education', 'Marital_Status', 'Age', 'Pay_Status_Sept', 'Pay_Status_Aug', 'Pay_Status_July', 'Pay_Status_June', 'Pay_Status_May', 'Pay_Status_April', 'Bill_Sept', 'Bill_Aug', 'Bill_July', 'Bill_June', 'Bill_May', 'Bill_April', 'Payment_Sept', 'Payment_Aug', 'Payment_July', 'Payment_June', 'Payment_May', 'Payment_April', 'Default_Next_Month']

In [35]:
print("Shape:", df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nDuplicate Customer IDs:")
print(df["Customer_ID"].duplicated().sum())

Shape: (30000, 25)

Missing Values:
Customer_ID           0
Credit_Limit          0
Gender                0
Education             0
Marital_Status        0
Age                   0
Pay_Status_Sept       0
Pay_Status_Aug        0
Pay_Status_July       0
Pay_Status_June       0
Pay_Status_May        0
Pay_Status_April      0
Bill_Sept             0
Bill_Aug              0
Bill_July             0
Bill_June             0
Bill_May              0
Bill_April            0
Payment_Sept          0
Payment_Aug           0
Payment_July          0
Payment_June          0
Payment_May           0
Payment_April         0
Default_Next_Month    0
dtype: int64

Duplicate Rows:
0

Duplicate Customer IDs:
0

In [36]:
print("Gender:")
print(df["Gender"].value_counts())

print("\nEducation:")
print(df["Education"].value_counts())

print("\nMarital Status:")
print(df["Marital_Status"].value_counts())

print("\nDefault:")
print(df["Default_Next_Month"].value_counts())

Gender:
Gender
2    18112
1    11888
Name: count, dtype: int64

Education:
Education
2    14030
1    10585
3     4917
5      280
4      123
6       51
0       14
Name: count, dtype: int64

Marital Status:
Marital_Status
2    15964
1    13659
3      323
0       54
Name: count, dtype: int64

Default:
Default_Next_Month
0    23364
1     6636
Name: count, dtype: int64

In [37]:
df["Gender"] = df["Gender"].map({
    1: "Male",
    2: "Female"
})

In [38]:
df["Education"] = df["Education"].map({
    0: "Unknown",
    1: "Graduate School",
    2: "University",
    3: "High School",
    4: "Others",
    5: "Unknown",
    6: "Unknown"
})

In [39]:
df["Marital_Status"] = df["Marital_Status"].map({
    0: "Unknown",
    1: "Married",
    2: "Single",
    3: "Others"
})

In [40]:
bill_columns = [
    "Bill_Sept",
    "Bill_Aug",
    "Bill_July",
    "Bill_June",
    "Bill_May",
    "Bill_April"
]

df["Total_Billed_6M"] = df[bill_columns].sum(axis=1)

print(df["Total_Billed_6M"])

0          7704
1         17077
2        101653
3        231334
4        109339
          ...
29995    725349
29996     21182
29997     70496
29998    266611
29999    230874
Name: Total_Billed_6M, Length: 30000, dtype: int64

In [41]:
df["Avg_Monthly_Bill"] = df[bill_columns].mean(axis=1)
print(df["Avg_Monthly_Bill"])

0          1284.000000
1          2846.166667
2         16942.166667
3         38555.666667
4         18223.166667
             ...
29995    120891.500000
29996      3530.333333
29997     11749.333333
29998     44435.166667
29999     38479.000000
Name: Avg_Monthly_Bill, Length: 30000, dtype: float64

In [42]:
payment_columns = [
    "Payment_Sept",
    "Payment_Aug",
    "Payment_July",
    "Payment_June",
    "Payment_May",
    "Payment_April"
]

df["Total_Paid_6M"] = df[payment_columns].sum(axis=1)
print(df["Total_Paid_6M"])

0           689
1          5000
2         11018
3          8388
4         59049
          ...
29995     42550
29996     14490
29997     31300
29998    147181
29999      8308
Name: Total_Paid_6M, Length: 30000, dtype: int64

In [43]:
df["Avg_Monthly_Payment"] = (
    df[payment_columns].mean(axis=1)
)
print(df["Avg_Monthly_Payment"])

0          114.833333
1          833.333333
2         1836.333333
3         1398.000000
4         9841.500000
             ...
29995     7091.666667
29996     2415.000000
29997     5216.666667
29998    24530.166667
29999     1384.666667
Name: Avg_Monthly_Payment, Length: 30000, dtype: float64

In [44]:
df["Credit_Utilization"] = (
    df["Avg_Monthly_Bill"] /
    df["Credit_Limit"]
) * 100
print(df["Credit_Utilization"])

0         6.420000
1         2.371806
2        18.824630
3        77.111333
4        36.446333
           ...
29995    54.950682
29996     2.353556
29997    39.164444
29998    55.543958
29999    76.958000
Name: Credit_Utilization, Length: 30000, dtype: float64

In [45]:
pay_columns = [
    "Pay_Status_Sept",
    "Pay_Status_Aug",
    "Pay_Status_July",
    "Pay_Status_June",
    "Pay_Status_May",
    "Pay_Status_April"
]

df["Avg_Payment_Status"] = (
    df[pay_columns].mean(axis=1)
)

In [46]:
def assign_segment(row):

    if row["Credit_Limit"] >= 200000 and row["Credit_Utilization"] < 50:
        return "Premium"

    elif row["Credit_Limit"] >= 100000 and row["Credit_Utilization"] < 75:
        return "High Value"

    elif row["Credit_Utilization"] >= 75:
        return "High Utilization"

    else:
        return "Standard"

In [47]:
df["Customer_Segment"] = df.apply(
    assign_segment,
    axis=1
)

In [48]:
print(df["Customer_Segment"].value_counts())

Customer_Segment
Premium             9164
Standard            7715
High Value          6939
High Utilization    6182
Name: count, dtype: int64

In [49]:
customers = df[
    [
        "Customer_ID",
        "Credit_Limit",
        "Gender",
        "Education",
        "Marital_Status",
        "Age",
        "Total_Billed_6M",
        "Avg_Monthly_Bill",
        "Total_Paid_6M",
        "Avg_Monthly_Payment",
        "Credit_Utilization",
        "Avg_Payment_Status",
        "Default_Next_Month",
        "Customer_Segment"
    ]
].copy()

In [50]:
customers.head()

,Customer_ID,Credit_Limit,Gender,Education,Marital_Status,Age,Total_Billed_6M,Avg_Monthly_Bill,Total_Paid_6M,Avg_Monthly_Payment,Credit_Utilization,Avg_Payment_Status,Default_Next_Month,Customer_Segment
0,1,20000,Female,University,Married,24,7704,1284.000000,689,114.833333,6.420000,-0.333333,1,Standard
1,2,120000,Female,University,Single,26,17077,2846.166667,5000,833.333333,2.371806,0.500000,1,High Value
2,3,90000,Female,University,Single,34,101653,16942.166667,11018,1836.333333,18.824630,0.000000,0,Standard
3,4,50000,Female,University,Married,37,231334,38555.666667,8388,1398.000000,77.111333,0.000000,0,High Utilization
4,5,50000,Male,University,Married,57,109339,18223.166667,59049,9841.500000,36.446333,-0.333333,0,Standard

In [51]:
customers.to_csv(
    "customers.csv",
    index=False
)

In [52]:
print(customers.shape)
print(customers.columns.tolist())

(30000, 14)
['Customer_ID', 'Credit_Limit', 'Gender', 'Education', 'Marital_Status', 'Age', 'Total_Billed_6M', 'Avg_Monthly_Bill', 'Total_Paid_6M', 'Avg_Monthly_Payment', 'Credit_Utilization', 'Avg_Payment_Status', 'Default_Next_Month', 'Customer_Segment']

In [53]:
np.random.seed(42)

In [54]:
num_transactions = 120000

In [55]:
customer_weights = customers["Credit_Utilization"].clip(lower=5, upper=100)

customer_weights = customer_weights / customer_weights.sum()

transaction_customers = np.random.choice(
    customers["Customer_ID"],
    size=num_transactions,
    replace=True,
    p=customer_weights
)

In [56]:
transaction_customers[:10]

array([11493, 28504, 21723, 17873,  4829,  4829,  1844, 25985, 17931,
       21070])

In [57]:
transactions = pd.DataFrame({
    "Transaction_ID": range(1, num_transactions + 1),
    "Customer_ID": transaction_customers
})
print(transactions.shape)
print(transactions.head())

(120000, 2)
   Transaction_ID  Customer_ID
0               1        11493
1               2        28504
2               3        21723
3               4        17873
4               5         4829

In [58]:
transactions = transactions.merge(
    customers[
        [
            "Customer_ID",
            "Credit_Limit",
            "Age",
            "Customer_Segment",
            "Credit_Utilization",
            "Avg_Payment_Status"
        ]
    ],
    on="Customer_ID",
    how="left"
)
print(transactions.head())

   Transaction_ID  Customer_ID  Credit_Limit  Age  Customer_Segment  \
0               1        11493        320000   37        High Value
1               2        28504        150000   36        High Value
2               3        21723         20000   22  High Utilization
3               4        17873         60000   28          Standard
4               5         4829         90000   28          Standard

   Credit_Utilization  Avg_Payment_Status
0           54.493750            0.000000
1           74.098111            2.000000
2           89.421667            0.000000
3           42.226667            0.000000
4           68.243333           -0.166667

In [59]:
np.random.randint(100, 10000)

3807

In [60]:
base_amount = transactions["Credit_Limit"] * np.random.uniform(
    0.01, 0.08, size=num_transactions
)

In [61]:
transactions["Transaction_Amount"] = (
    base_amount * np.random.uniform(0.7, 1.3, size=num_transactions)
)

In [62]:
transactions["Transaction_Amount"] = (
    transactions["Transaction_Amount"]
    .clip(lower=50)
    .round(2)
)

In [63]:
print(
    transactions[
        ["Customer_ID", "Credit_Limit", "Transaction_Amount"]
    ].head(10)
)

   Customer_ID  Credit_Limit  Transaction_Amount
0        11493        320000             7920.84
1        28504        150000            13349.33
2        21723         20000             1414.74
3        17873         60000             5949.76
4         4829         90000             2228.93
5         4829         90000             8282.71
6         1844         20000              659.14
7        25985         30000              338.58
8        17931         20000              657.16
9        21070        380000            10511.78

In [64]:
categories = [
    "Grocery",
    "Dining",
    "Travel",
    "Shopping",
    "Electronics",
    "Healthcare",
    "Utilities",
    "Entertainment"
]

transactions["Transaction_Category"] = np.random.choice(
    categories,
    size=num_transactions,
    p=[0.18, 0.14, 0.10, 0.20, 0.08, 0.08, 0.12, 0.10]
)

In [65]:
transaction_dates = pd.date_range(
    start="2025-01-01",
    end="2025-12-31",
    periods=num_transactions
)

transactions["Transaction_Date"] = transaction_dates

In [66]:
start_date = pd.Timestamp("2025-01-01")
end_date = pd.Timestamp("2025-12-31")

random_days = np.random.randint(
    0,
    (end_date - start_date).days + 1,
    size=num_transactions
)

transactions["Transaction_Date"] = (
    start_date + pd.to_timedelta(random_days, unit="D")
)

In [67]:
channels = [
    "Online",
    "POS",
    "Mobile App",
    "Contactless"
]

transactions["Channel"] = np.random.choice(
    channels,
    size=num_transactions,
    p=[0.35, 0.35, 0.15, 0.15]
)

In [68]:
transactions["Rewards_Earned"] = (
    transactions["Transaction_Amount"] * 0.01
).round(2)

In [69]:
transactions["Transaction_Status"] = np.random.choice(
    ["Approved", "Declined"],
    size=num_transactions,
    p=[0.95, 0.05]
)

In [70]:
transactions = transactions[
    [
        "Transaction_ID",
        "Customer_ID",
        "Transaction_Date",
        "Transaction_Category",
        "Channel",
        "Transaction_Amount",
        "Rewards_Earned",
        "Transaction_Status",
        "Credit_Limit",
        "Age",
        "Customer_Segment",
        "Credit_Utilization",
        "Avg_Payment_Status"
    ]
]

In [71]:
print("Rows:", transactions.shape[0])
print("Columns:", transactions.shape[1])

print("\nMissing values:")
print(transactions.isnull().sum())

print("\nFirst 10 records:")
print(transactions.head(10))

Rows: 120000
Columns: 13

Missing values:
Transaction_ID          0
Customer_ID             0
Transaction_Date        0
Transaction_Category    0
Channel                 0
Transaction_Amount      0
Rewards_Earned          0
Transaction_Status      0
Credit_Limit            0
Age                     0
Customer_Segment        0
Credit_Utilization      0
Avg_Payment_Status      0
dtype: int64

First 10 records:
   Transaction_ID  Customer_ID Transaction_Date Transaction_Category  \
0               1        11493       2025-06-01        Entertainment
1               2        28504       2025-01-21            Utilities
2               3        21723       2025-01-14             Shopping
3               4        17873       2025-08-19            Utilities
4               5         4829       2025-01-21              Grocery
5               6         4829       2025-05-26             Shopping
6               7         1844       2025-03-19          Electronics
7               8        25985       2025-03-18               Travel
8               9        17931       2025-08-27             Shopping
9              10        21070       2025-12-23               Dining

       Channel  Transaction_Amount  Rewards_Earned Transaction_Status  \
0          POS             7920.84           79.21           Approved
1  Contactless            13349.33          133.49           Approved
2       Online             1414.74           14.15           Approved
3          POS             5949.76           59.50           Approved
4          POS             2228.93           22.29           Approved
5          POS             8282.71           82.83           Approved
6       Online              659.14            6.59           Approved
7       Online              338.58            3.39           Approved
8       Online              657.16            6.57           Approved
9   Mobile App            10511.78          105.12           Approved

   Credit_Limit  Age  Customer_Segment  Credit_Utilization  Avg_Payment_Status
0        320000   37        High Value           54.493750            0.000000
1        150000   36        High Value           74.098111            2.000000
2         20000   22  High Utilization           89.421667            0.000000
3         60000   28          Standard           42.226667            0.000000
4         90000   28          Standard           68.243333           -0.166667
5         90000   28          Standard           68.243333           -0.166667
6         20000   41  High Utilization           95.099167           -0.666667
7         30000   46  High Utilization           79.128889            1.000000
8         20000   31  High Utilization           79.521667            0.333333
9        380000   40        High Value           62.025614            0.000000

In [72]:
transactions.to_csv("transactions.csv", index=False)

In [73]:
campaigns = pd.DataFrame({
    "Campaign_ID": range(1, 11),

    "Campaign_Name": [
        "Cashback Plus",
        "Travel Rewards",
        "Dining Rewards",
        "Premium Upgrade",
        "Balance Transfer",
        "Festival Cashback",
        "Fuel Savings",
        "Shopping Rewards",
        "Credit Limit Increase",
        "Digital Engagement"
    ],

    "Campaign_Type": [
        "Cashback",
        "Rewards",
        "Rewards",
        "Upsell",
        "Balance Transfer",
        "Cashback",
        "Rewards",
        "Rewards",
        "Credit Limit",
        "Engagement"
    ],

    "Target_Segment": [
        "High Value",
        "Premium",
        "Standard",
        "Premium",
        "High Utilization",
        "Standard",
        "High Utilization",
        "High Value",
        "High Utilization",
        "Standard"
    ]
})
print(campaigns)

   Campaign_ID          Campaign_Name     Campaign_Type    Target_Segment
0            1          Cashback Plus          Cashback        High Value
1            2         Travel Rewards           Rewards           Premium
2            3         Dining Rewards           Rewards          Standard
3            4        Premium Upgrade            Upsell           Premium
4            5       Balance Transfer  Balance Transfer  High Utilization
5            6      Festival Cashback          Cashback          Standard
6            7           Fuel Savings           Rewards  High Utilization
7            8       Shopping Rewards           Rewards        High Value
8            9  Credit Limit Increase      Credit Limit  High Utilization
9           10     Digital Engagement        Engagement          Standard

In [74]:
campaigns["Start_Date"] = pd.to_datetime([
    "2025-01-15",
    "2025-02-01",
    "2025-03-01",
    "2025-04-01",
    "2025-05-01",
    "2025-06-01",
    "2025-07-01",
    "2025-08-01",
    "2025-09-01",
    "2025-10-01"
])

campaigns["End_Date"] = campaigns["Start_Date"] + pd.Timedelta(days=30)

In [75]:
campaigns["Campaign_Budget"] = [
    150000,
    200000,
    120000,
    250000,
    180000,
    175000,
    100000,
    160000,
    220000,
    90000
]

In [76]:
campaigns.to_csv("campaigns.csv", index=False)

In [77]:
print(campaigns.shape)
print(campaigns.head())

(10, 7)
   Campaign_ID     Campaign_Name     Campaign_Type    Target_Segment  \
0            1     Cashback Plus          Cashback        High Value
1            2    Travel Rewards           Rewards           Premium
2            3    Dining Rewards           Rewards          Standard
3            4   Premium Upgrade            Upsell           Premium
4            5  Balance Transfer  Balance Transfer  High Utilization

  Start_Date   End_Date  Campaign_Budget
0 2025-01-15 2025-02-14           150000
1 2025-02-01 2025-03-03           200000
2 2025-03-01 2025-03-31           120000
3 2025-04-01 2025-05-01           250000
4 2025-05-01 2025-05-31           180000

In [78]:
num_contacts = 50000

In [79]:
contact_customers = np.random.choice(
    customers["Customer_ID"],
    size=num_contacts,
    replace=True
)

In [80]:
contact_campaigns = np.random.choice(
    campaigns["Campaign_ID"],
    size=num_contacts,
    replace=True
)

In [81]:
campaign_contacts = pd.DataFrame({
    "Contact_ID": range(1, num_contacts + 1),
    "Customer_ID": contact_customers,
    "Campaign_ID": contact_campaigns
})

In [82]:
channels = [
    "Email",
    "SMS",
    "Mobile App",
    "Phone",
    "Web"
]

campaign_contacts["Channel"] = np.random.choice(
    channels,
    size=num_contacts,
    p=[0.30, 0.20, 0.25, 0.10, 0.15]
)

In [83]:
campaign_contacts["Response"] = np.random.choice(
    [0, 1],
    size=num_contacts,
    p=[0.75, 0.25]
)

In [84]:
campaign_contacts["Conversion"] = np.where(
    campaign_contacts["Response"] == 1,
    np.random.choice([0, 1], size=num_contacts, p=[0.60, 0.40]),
    0
)

In [85]:
print(
    campaign_contacts["Response"].value_counts()
)

print(
    campaign_contacts["Conversion"].value_counts()
)

Response
0    37592
1    12408
Name: count, dtype: int64
Conversion
0    45117
1     4883
Name: count, dtype: int64

In [86]:
response_rate = campaign_contacts["Response"].mean()

print("Overall Response Rate:", response_rate)

Overall Response Rate: 0.24816

In [87]:
conversion_rate = (
    campaign_contacts["Conversion"].sum()
    / campaign_contacts["Response"].sum()
)

print("Conversion Rate:", conversion_rate)

Conversion Rate: 0.3935364281108962

In [88]:
channel_cost = {
    "Email": 5,
    "SMS": 8,
    "Mobile App": 3,
    "Phone": 25,
    "Web": 2
}
campaign_contacts["Contact_Cost"] = (
    campaign_contacts["Channel"].map(channel_cost)
)

In [89]:
print(campaign_contacts.head())
print(campaign_contacts.shape)

   Contact_ID  Customer_ID  Campaign_ID     Channel  Response  Conversion  \
0           1        20008            5         SMS         0           0
1           2        27856            3         Web         0           0
2           3        15059            1  Mobile App         0           0
3           4        22163            8         Web         0           0
4           5        21446            4       Email         0           0

   Contact_Cost
0             8
1             2
2             3
3             2
4             5
(50000, 7)

In [90]:
print(customers.shape)
print(transactions.shape)
print(campaigns.shape)
print(campaign_contacts.shape)

(30000, 14)
(120000, 13)
(10, 7)
(50000, 7)

In [91]:
converted_contacts = campaign_contacts[
    campaign_contacts["Conversion"] == 1
].copy()
print(converted_contacts.shape)
print(converted_contacts.head())

(4883, 7)
    Contact_ID  Customer_ID  Campaign_ID Channel  Response  Conversion  \
5            6        18403            3   Email         1           1
22          23        21681           10   Email         1           1
37          38         7499            3     SMS         1           1
59          60        25247           10     SMS         1           1
63          64        15025            1   Email         1           1

    Contact_Cost
5              5
22             5
37             8
59             8
63             5

In [92]:
campaign_transactions = transactions.merge(
    converted_contacts[
        [
            "Contact_ID",
            "Customer_ID",
            "Campaign_ID",
            "Channel"
        ]
    ],
    on="Customer_ID",
    how="inner"
)

In [93]:
transactions["Transaction_Amount"]

0          7920.84
1         13349.33
2          1414.74
3          5949.76
4          2228.93
            ...
119995     3885.33
119996    14068.47
119997      247.64
119998    23266.08
119999    11443.18
Name: Transaction_Amount, Length: 120000, dtype: float64

In [94]:
campaign_transactions["Revenue"] = (
    campaign_transactions["Transaction_Amount"]
)

In [95]:
print(
    campaign_transactions[
        [
            "Customer_ID",
            "Campaign_ID",
            "Transaction_Amount",
            "Revenue"
        ]
    ].head()
)

   Customer_ID  Campaign_ID  Transaction_Amount   Revenue
0        28504            4            13349.33  13349.33
1         1844            2              659.14    659.14
2         1844            6              659.14    659.14
3         1466            9             7372.87   7372.87
4        18081            7             7661.40   7661.40

In [96]:
campaign_revenue = (
    campaign_transactions
    .groupby("Campaign_ID")
    .agg(
        Total_Revenue=("Revenue", "sum"),
        Revenue_Transactions=("Transaction_ID", "count"),
        Unique_Customers=("Customer_ID", "nunique")
    )
    .reset_index()
)
print(campaign_revenue)

   Campaign_ID  Total_Revenue  Revenue_Transactions  Unique_Customers
0            1    11867004.34                  2005               374
1            2    10725491.89                  1949               382
2            3    10519283.43                  1940               347
3            4    10466406.48                  1918               389
4            5    11533041.43                  2194               385
5            6     9383973.83                  1777               342
6            7    11611615.56                  2055               366
7            8    10930040.48                  1873               369
8            9     9769698.82                  1810               349
9           10    11337736.17                  2230               413

In [97]:
campaign_contacts["Contact_Cost"]

0        8
1        2
2        3
3        2
4        5
        ..
49995    5
49996    5
49997    5
49998    5
49999    8
Name: Contact_Cost, Length: 50000, dtype: int64

In [98]:
campaign_cost = (
    campaign_contacts
    .groupby("Campaign_ID")
    .agg(
        Total_Cost=("Contact_Cost", "sum"),
        Total_Contacts=("Contact_ID", "count"),
        Total_Responses=("Response", "sum"),
        Total_Conversions=("Conversion", "sum")
    )
    .reset_index()
)
print(campaign_cost)

   Campaign_ID  Total_Cost  Total_Contacts  Total_Responses  Total_Conversions
0            1       33485            4927             1224                505
1            2       32937            4945             1214                483
2            3       32825            4978             1188                468
3            4       33415            5040             1305                510
4            5       33085            5000             1214                498
5            6       34287            5061             1212                449
6            7       33404            5087             1268                466
7            8       33040            4968             1252                491
8            9       33078            4935             1206                478
9           10       33342            5059             1325                535

In [99]:
campaign_performance = campaign_cost.merge(
    campaign_revenue,
    on="Campaign_ID",
    how="left"
)

In [100]:
campaign_performance["Total_Revenue"] = (
    campaign_performance["Total_Revenue"].fillna(0)
)

In [101]:
campaign_performance["Net_Revenue"] = (
    campaign_performance["Total_Revenue"]
    - campaign_performance["Total_Cost"]
)

In [102]:
campaign_performance["ROI"] = (
    campaign_performance["Net_Revenue"]
    / campaign_performance["Total_Cost"]
) * 100

In [103]:
campaign_performance["Response_Rate"] = (
    campaign_performance["Total_Responses"]
    / campaign_performance["Total_Contacts"]
) * 100

In [104]:
campaign_performance["Conversion_Rate"] = (
    campaign_performance["Total_Conversions"]
    / campaign_performance["Total_Responses"]
).replace([np.inf, -np.inf], 0).fillna(0) * 100

In [105]:
campaign_performance = campaign_performance.merge(
    campaigns[
        [
            "Campaign_ID",
            "Campaign_Name",
            "Campaign_Type",
            "Target_Segment"
        ]
    ],
    on="Campaign_ID",
    how="left"
)

In [107]:
campaign_performance = campaign_performance[
    [
        "Campaign_ID",
        "Campaign_Name",
        "Campaign_Type",
        "Target_Segment",
        "Total_Contacts",
        "Total_Responses",
        "Response_Rate",
        "Total_Conversions",
        "Conversion_Rate",
        "Unique_Customers",
        "Total_Revenue",
        "Total_Cost",
        "Net_Revenue",
        "ROI"
    ]
]
print(campaign_performance)

   Campaign_ID          Campaign_Name     Campaign_Type    Target_Segment  \
0            1          Cashback Plus          Cashback        High Value
1            2         Travel Rewards           Rewards           Premium
2            3         Dining Rewards           Rewards          Standard
3            4        Premium Upgrade            Upsell           Premium
4            5       Balance Transfer  Balance Transfer  High Utilization
5            6      Festival Cashback          Cashback          Standard
6            7           Fuel Savings           Rewards  High Utilization
7            8       Shopping Rewards           Rewards        High Value
8            9  Credit Limit Increase      Credit Limit  High Utilization
9           10     Digital Engagement        Engagement          Standard

   Total_Contacts  Total_Responses  Response_Rate  Total_Conversions  \
0            4927             1224      24.842703                505
1            4945             1214      24.550051                483
2            4978             1188      23.865006                468
3            5040             1305      25.892857                510
4            5000             1214      24.280000                498
5            5061             1212      23.947836                449
6            5087             1268      24.926283                466
7            4968             1252      25.201288                491
8            4935             1206      24.437690                478
9            5059             1325      26.190947                535

   Conversion_Rate  Unique_Customers  Total_Revenue  Total_Cost  Net_Revenue  \
0        41.258170               374    11867004.34       33485  11833519.34
1        39.785832               382    10725491.89       32937  10692554.89
2        39.393939               347    10519283.43       32825  10486458.43
3        39.080460               389    10466406.48       33415  10432991.48
4        41.021417               385    11533041.43       33085  11499956.43
5        37.046205               342     9383973.83       34287   9349686.83
6        36.750789               366    11611615.56       33404  11578211.56
7        39.217252               369    10930040.48       33040  10897000.48
8        39.635158               349     9769698.82       33078   9736620.82
9        40.377358               413    11337736.17       33342  11304394.17

            ROI
0  35339.762102
1  32463.657558
2  31946.560335
3  31222.479366
4  34758.822518
5  27268.897337
6  34661.153036
7  32981.236320
8  29435.337143
9  33904.367374

In [108]:
campaign_performance.to_csv(
    "campaign_performance.csv",
    index=False
)

In [109]:
campaign_contacts.to_csv("campaign_contacts.csv", index=False)

print("Campaign contacts saved successfully!")

Campaign contacts saved successfully!